### ISSUE TITLE
starts-spark does not start Spark

### ISSUE THREAD

**Issue by rvernica** [SingularitiesCR/spark-docker#3]
Just running `start-spark master` does not start Spark:
```
> docker run -ti --rm singularities/spark bash
root@742c0b1c2bf3:/# start-spark master
Adding user `spark' ...
Adding new group `spark' (1000) ...
Adding new user `spark' (1000) with group `spark' ...
Not creating home directory `/home/spark'.
spark@742c0b1c2bf3:/$ 
```
But if I exit the shell, HDFS and Spark start:
```
spark@742c0b1c2bf3:/$ exit
16/12/20 22:18:56 INFO namenode.NameNode: STARTUP_MSG: 
/************************************************************
STARTUP_MSG: Starting NameNode
STARTUP_MSG:   host = 742c0b1c2bf3/172.17.0.3
STARTUP_MSG:   args = [-format, -force]
STARTUP_MSG:   version = 2.7.3
...
16/12/20 22:19:17 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@23a44d8a{/metrics/applications/json,null,AVAILABLE}
16/12/20 22:19:17 INFO master.Master: I have been elected leader! New state: ALIVE
```

**Comment by fjhoelsg** [comment]
We had never tried running this image in an interactive shell. The error was caused by [a bug](https://github.com/SingularitiesCR/hadoop-docker/commit/c1377f83ec29a78a3ecdde068bd948413ee0ddd8) in the [Hadoop image](https://github.com/SingularitiesCR/hadoop-docker).  Thank you for raising this issue; otherwise, we would not have found the bug in the base image.

Try pulling the new version of the image, and if the problem continues please reopen the issue.
