### ISSUE TITLE
worker webui not accessable

### ISSUE THREAD

**Issue by fryder** [SingularitiesCR/spark-docker#9]
Hi,
First,this is a great code to use for spark and hadoop.
Congratulations and thanks for a good dependable spark docker package.
I was trying to access worker ui,as we cannot add a port to expose worker api to be able to scale,
how can we access webui..for example the ipaddress of the container like workerIP:8081 is also not working.
Please help

**Comment by fjhoelsg** [comment]
Hi @fryder,

We are pleased to hear that you have found these images useful. Indeed, using the worker Web UI has been an issue since we created the images. As far as I know, the best way to deal with this is by registering several worker services in a Docker Compose file, each with a different port mapping for the Web UI.

From what I have seen there is no way to configure a dynamic port mapping for services that must be scaled. One could setup some sort of web proxy in a container to access the Web UI, but I don't think it is worth the hassle.
